language: java

jdk:
  - oraclejdk8

script:
  - ./gradlew clean assemble check -Dpre-dex=false --stacktrace

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle

